name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest & windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make create
      run: make run
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
